server:
  port: 8080

spring:
  datasource:
#      name: test
#      url: jdbc:mysql://www.angelyb.com:3306/internetCafe?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=true
#      username: root
#      password: root
#      # 使用druid数据源
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
      name: test
      url: jdbc:mysql://www.angelyb.com:3306/internetCafe?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml #xml位置
  type-aliases-package: com.ttzf.model #实体类的路径

#pagehelper:
#  reasonable: true
#  helperDialect: mysql
#  supportMethodsArguments: true
#  params: count=countSql
