create table menu_table(
  ID VARCHAR(64) PRIMARY KEY NOT NULL ,
  MENU_NAME VARCHAR(64),
  MENU_URL VARCHAR(64),
  LEVEL INT,
  LAST_MENU_ID VARCHAR(64),
  LAST_MENU_NAME VARCHAR(64),
  STATE INT,
  AUTH VARCHAR(64)
);